name = "hexxytest3"
author = "chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bad896c7a844655a1f214a04e26691a0c166887be34e80cc9222b619672f341e"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
